# Generated by Django 5.0.7 on 2024-07-26 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vacinacao", "0002_alter_criancas_vacina"),
    ]

    operations = [
        migrations.AddField(
            model_name="criancas",
            name="bairro",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="criancas",
            name="vacina",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
